package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/manifoldco/promptui"
	"github.com/spf13/cobra"
	"github.com/your-org/atom/atom-cli/internal/config"
	"github.com/your-org/atom/atom-cli/internal/deploy"
)

var deployCmd = &cobra.Command{
	Use:   "deploy",
	Short: "Build and deploy the agent in the current directory",
	Long: `Builds a Docker image locally and submits a deployment to atom-studio.
An admin must approve it in the HITL queue before atom-runtime starts the container.

── Build ────────────────────────────────────────────────────────────────────
  docker build runs on the local machine using the Dockerfile in the current
  directory. The built image is referenced by name when submitted to studio.

── atom_agent.yaml ──────────────────────────────────────────────────────────
Generated by atom create. Fill in agent_id and domain_id from atom-studio.

  agent_id: ""
  domain_id: ""
  sdk_image: ""   # optional — base image tag for your Dockerfile

── After deploy ─────────────────────────────────────────────────────────────
Go to atom-studio → HITL queue → Approve to start the container.
Then stream logs: atom logs <agent-id>

Examples:
  atom deploy                                  # reads atom_agent.yaml
  atom deploy --message "hotfix"               # custom message
  atom deploy --skip-build --image my-img:tag  # skip build, use existing image`,
	RunE: runDeploy,
}

var (
	deployAgentID string
	deployImage   string
	deployMessage string
	deploySkip    bool
)

func init() {
	deployCmd.Flags().StringVar(&deployAgentID, "agent-id", "", "Agent UUID (reads from atom_agent.yaml or ATOM_AGENT_ID env)")
	deployCmd.Flags().StringVar(&deployImage, "image", "", "Docker image name (defaults to project directory name)")
	deployCmd.Flags().StringVar(&deployMessage, "message", "", "Deployment message / changelog")
	deployCmd.Flags().BoolVar(&deploySkip, "skip-build", false, "Skip docker build and use existing image")
}

func runDeploy(_ *cobra.Command, _ []string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	agentCfg, _ := readAgentConfig()

	// Resolve agent ID: flag > atom_agent.yaml > .env > prompt
	agentID := deployAgentID
	if agentID == "" && agentCfg != nil {
		agentID = agentCfg.AgentID
	}
	if agentID == "" {
		agentID = envFromDotfile("ATOM_AGENT_ID")
	}
	if agentID == "" {
		agentID, err = (&promptui.Prompt{
			Label: "Agent ID (from atom-studio)",
			Validate: func(s string) error {
				if strings.TrimSpace(s) == "" {
					return fmt.Errorf("required")
				}
				return nil
			},
		}).Run()
		if err != nil {
			return err
		}
		agentID = strings.TrimSpace(agentID)
	}

	// Resolve deployment message
	message := deployMessage
	if message == "" {
		message, err = (&promptui.Prompt{
			Label:   "Deployment message",
			Default: "deploy",
		}).Run()
		if err != nil {
			return err
		}
	}

	sdkImage := ""
	if agentCfg != nil {
		sdkImage = agentCfg.SDKImage
	}

	image, err := runLocalBuild(sdkImage)
	if err != nil {
		return err
	}

	fmt.Printf("Submitting deployment to %s ...\n", cfg.StudioURL)
	resp, err := deploy.Submit(cfg.StudioURL, cfg.AccessToken, agentID, image, message)
	if err != nil {
		return err
	}

	fmt.Printf("✓ Deployment submitted\n")
	if resp.ID != "" {
		fmt.Printf("  ID:     %s\n", resp.ID)
	}
	fmt.Printf("  Image:  %s\n", image)
	fmt.Printf("  Status: pending HITL approval\n\n")
	fmt.Printf("Next: approve at %s/hitl\n", strings.Replace(cfg.StudioURL, ":3001", ":3000", 1))
	return nil
}

func runLocalBuild(sdkImage string) (string, error) {
	if deploySkip {
		image := deployImage
		if image == "" {
			dir, _ := os.Getwd()
			image = filepath.Base(dir) + ":latest"
		}
		return image, nil
	}
	image := deployImage
	if image == "" {
		dir, _ := os.Getwd()
		image = filepath.Base(dir) + ":latest"
	}
	fmt.Printf("Building image %s locally ...\n", image)
	var buildArgs []string
	if sdkImage != "" {
		buildArgs = append(buildArgs, "--build-arg", "SDK_IMAGE="+sdkImage)
	}
	if err := deploy.BuildImageWithArgs(".", image, buildArgs); err != nil {
		return "", err
	}
	fmt.Printf("✓ Image built: %s\n\n", image)
	return image, nil
}

// envFromDotfile reads a KEY=VALUE entry from .env in the current directory.
func envFromDotfile(key string) string {
	data, err := os.ReadFile(".env")
	if err != nil {
		return ""
	}
	prefix := key + "="
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(line, prefix))
		}
	}
	return ""
}

// agentConfig holds the parsed fields from atom_agent.yaml that deploy needs.
type agentConfig struct {
	AgentID  string
	SDKImage string
}

// readAgentConfig parses atom_agent.yaml from the current directory.
// Returns nil (no error) if the file does not exist.
func readAgentConfig() (*agentConfig, error) {
	data, err := os.ReadFile("atom_agent.yaml")
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	cfg := &agentConfig{}
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		cfg.AgentID = parseYAMLField(trimmed, "agent_id", cfg.AgentID)
		cfg.SDKImage = parseYAMLField(trimmed, "sdk_image", cfg.SDKImage)
	}
	return cfg, nil
}

// parseYAMLField extracts a scalar value from a "key: value" YAML line.
// Strips inline comments (# …) from unquoted values.
// Returns current if the line does not match key.
func parseYAMLField(line, key, current string) string {
	prefix := key + ":"
	if !strings.HasPrefix(line, prefix) {
		return current
	}
	val := strings.TrimSpace(strings.TrimPrefix(line, prefix))
	val = strings.Trim(val, `"'`)
	if idx := strings.Index(val, " #"); idx != -1 {
		val = strings.TrimSpace(val[:idx])
	} else if idx := strings.Index(val, "\t#"); idx != -1 {
		val = strings.TrimSpace(val[:idx])
	}
	if val == "" {
		return current
	}
	return val
}
