import asyncio
import hashlib
import json
import logging
from typing import AsyncGenerator

import httpx

from ..config import get_settings
from ..database import get_conn
from ..services.builder_conversation import BuilderState, save_state
from ..services.builder import build_agent_py_prompt
from ..services.gitlab_service import GitLabService
from ..agents.service import AgentCreatePayload, create_agent, issue_agent_jwt
from ..deployments.service import get_runtime_url

log = logging.getLogger(__name__)

_CODEGEN_MODEL = "gemini-3.1-pro-preview"

# ── Helper ─────────────────────────────────────────────────────────────────────


def _progress(step: str, message: str, **extra) -> dict:
    return {"type": "progress", "step": step, "message": message, **extra}


# ── Scaffold file builders ─────────────────────────────────────────────────────


def _build_atom_agent_yaml(state: BuilderState, gitlab_group: str) -> str:
    return f"""# Agent configuration — generated by ATOM Builder
agent_id: "{state.agent_id}"
domain_id: "{state.domain_id}"
model: "{state.model}"
ci_provider: "{state.ci_target}"
sdk_image: "registry.gitlab.com/{gitlab_group}/atom-sdk:latest"
"""


def _build_dockerfile(gitlab_group: str) -> str:
    return f"""ARG SDK_IMAGE=registry.gitlab.com/{gitlab_group}/atom-sdk:latest
FROM ${{SDK_IMAGE}} AS sdk
FROM python:3.11-slim
WORKDIR /app
COPY --from=sdk /atom-sdk /atom-sdk
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["python", "agent.py"]
"""


def _build_gitlab_ci() -> str:
    return """stages: [build]

atom-build:
  stage: build
  image: docker:24
  services: [docker:24-dind]
  variables:
    DOCKER_BUILDKIT: "1"
  rules:
    - if: '$ATOM_BUILD == "true"'
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build
        --build-arg SDK_IMAGE=${SDK_IMAGE:-python:3.11-slim}
        -t $CI_REGISTRY_IMAGE:$ATOM_IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$ATOM_IMAGE_TAG
"""


def _build_requirements() -> str:
    return "agentscope>=0.1.0\nfastapi>=0.110.0\nuvicorn>=0.29.0\n"


def _build_readme(state: BuilderState) -> str:
    return (
        f"# {state.agent_name}\n\nGenerated by ATOM Builder.\n\n## Intent\n{state.intent or ''}\n"
    )


# ── Local Docker build ────────────────────────────────────────────────────────


async def _build_local_image(state: BuilderState, agent_py: str) -> tuple[str, str]:
    """
    Write scaffold files to a temp directory, run `docker build`, return (image_tag, log).
    Uses the host Docker socket (mounted at /var/run/docker.sock in dev).
    """
    import tempfile
    import os
    import docker as docker_sdk

    image_name = (state.agent_name or state.agent_id or "agent").lower().replace(" ", "-")
    image_tag = f"atom-agent/{image_name}:latest"

    # Use atom-sdk:local as base — it has agentscope pre-installed.
    # Fall back to python:3.11-slim if atom-sdk:local hasn't been built yet.
    import docker as docker_sdk_check  # noqa: PLC0415

    _client_check = docker_sdk_check.from_env()
    try:
        _client_check.images.get("atom-sdk:local")
        base_image = "atom-sdk:local"
    except docker_sdk_check.errors.ImageNotFound:
        base_image = "python:3.11-slim"

    dockerfile_content = f"""FROM {base_image}
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["python", "agent.py"]
"""

    with tempfile.TemporaryDirectory() as tmpdir:
        files = {
            "agent.py": agent_py,
            "requirements.txt": _build_requirements(),
            "Dockerfile": dockerfile_content,
            "atom_agent.yaml": _build_atom_agent_yaml(state, ""),
            "README.md": _build_readme(state),
        }
        for name, content in files.items():
            with open(os.path.join(tmpdir, name), "w") as f:
                f.write(content)

        loop = asyncio.get_event_loop()

        def _docker_build():
            client = docker_sdk.from_env()
            _, log_output = client.images.build(
                path=tmpdir,
                tag=image_tag,
                rm=True,
                forcerm=True,
            )
            log_lines = [
                chunk.get("stream", chunk.get("status", ""))
                for chunk in log_output
                if isinstance(chunk, dict)
            ]
            return "\n".join(line for line in log_lines if line.strip())

        build_log = await loop.run_in_executor(None, _docker_build)

    return image_tag, build_log


# ── Direct deploy (bypasses HITL — builder-only path) ─────────────────────────


async def _direct_deploy(
    state: BuilderState,
    image: str,
    git_sha: str | None,
    message: str,
    owner_id: str,
) -> str:
    """
    Insert deployment row, issue a pod JWT, and call atom-runtime directly.
    Returns the deployment_id string.
    This bypasses the HITL approval queue — only used by the builder flow.
    """
    manifest = json.dumps({"image": image, "git_sha": git_sha, "message": message})

    async with get_conn() as conn:
        # Create deployment record
        deployment = await conn.fetchrow(
            """
            WITH v AS (
                SELECT COALESCE(MAX(version), 0) + 1 AS next_version
                FROM deployments WHERE agent_id = $1
            )
            INSERT INTO deployments (agent_id, version, manifest_json, status, submitted_by)
            SELECT $1, next_version, $2::jsonb, 'pending', $3::uuid
            FROM v
            RETURNING id
            """,
            state.agent_id,
            manifest,
            owner_id,
        )
        deployment_id = str(deployment["id"])

        # Issue fresh pod JWT, revoke old ones
        agent_jwt = issue_agent_jwt(state.agent_id, state.domain_id or "")
        token_hash = hashlib.sha256(agent_jwt.encode()).hexdigest()
        await conn.execute(
            "UPDATE agent_tokens SET revoked_at=now() WHERE agent_id=$1 AND revoked_at IS NULL AND token_type='pod'",
            state.agent_id,
        )
        await conn.execute(
            "INSERT INTO agent_tokens (agent_id, token_hash, token_type) VALUES ($1,$2,'pod')",
            state.agent_id,
            token_hash,
        )

    # Call atom-runtime directly
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(
            f"{get_runtime_url()}/runtime/deploy",
            json={
                "deployment_id": deployment_id,
                "agent_id": state.agent_id,
                "domain_id": state.domain_id or "",
                "image": image,
                "agent_jwt": agent_jwt,
            },
        )
        resp.raise_for_status()

    return deployment_id


# ── Main deploy generator ──────────────────────────────────────────────────────


async def run_deploy(
    state: BuilderState,
    owner_id: str,
    redis,
) -> AsyncGenerator[dict, None]:
    """
    8-step deploy sequence yielding SSE-ready event dicts.

    Yields _progress dicts for each step.
    On error yields {"type": "error", ...} and returns.
    """
    settings = get_settings()

    # ── Step 1: Provision agent in DB + LiteLLM ────────────────────────────────
    step = "provisioning"
    try:
        payload = AgentCreatePayload(
            name=state.agent_name or "unnamed-agent",
            description=state.intent,
            allowed_models=[state.model] if state.model else ["gemini-2.5-flash"],
        )
        agent_dict, _raw_jwt = await create_agent(
            state.domain_id or "",
            payload,
            owner_id,
        )
        state.agent_id = str(agent_dict["id"])
        yield _progress(step, f"Agent provisioned: {state.agent_id}")

        # Insert agent_tools and agent_skills associations
        if state.tools or state.skills:
            async with get_conn() as conn:
                for tool_name in state.tools:
                    row = await conn.fetchrow(
                        "SELECT id FROM tools WHERE name=$1 LIMIT 1", tool_name
                    )
                    if row:
                        await conn.execute(
                            "INSERT INTO agent_tools (agent_id, tool_id) VALUES ($1,$2) ON CONFLICT DO NOTHING",
                            state.agent_id,
                            row["id"],
                        )
                for skill_name in state.skills:
                    row = await conn.fetchrow(
                        "SELECT id FROM skills WHERE name=$1 LIMIT 1", skill_name
                    )
                    if row:
                        await conn.execute(
                            "INSERT INTO agent_skills (agent_id, skill_id) VALUES ($1,$2) ON CONFLICT DO NOTHING",
                            state.agent_id,
                            row["id"],
                        )

        await save_state(redis, state)

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Step 2: Codegen ────────────────────────────────────────────────────────
    step = "codegen"
    agent_py = ""
    try:
        # Fetch full tool objects from atom-llm
        tool_objects: list[dict] = []
        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                resp = await client.get(
                    f"{settings.atom_llm_url}/mcp/tools",
                    headers={"Authorization": f"Bearer {settings.litellm_master_key}"},
                )
                resp.raise_for_status()
                all_tools = resp.json()
                if isinstance(all_tools, dict):
                    all_tools = all_tools.get("tools", [])
                tool_objects = [t for t in all_tools if t.get("name") in state.tools]
        except Exception as fetch_exc:
            log.warning("codegen: could not fetch tools — %s", fetch_exc)

        # Fetch A2A agent details from DB
        a2a_details: list[dict] = []
        if state.a2a_targets:
            try:
                async with get_conn() as conn:
                    for target_name in state.a2a_targets:
                        row = await conn.fetchrow(
                            "SELECT id, name, description FROM agents WHERE name=$1 AND domain_id=$2",
                            target_name,
                            state.domain_id,
                        )
                        if row:
                            a2a_details.append(dict(row))
            except Exception as a2a_exc:
                log.warning("codegen: could not fetch A2A targets — %s", a2a_exc)

        codegen_prompt = build_agent_py_prompt(
            intent=state.intent or "",
            model_name=state.model or "gemini-2.5-flash",
            tools=tool_objects,
            skills=state.skills,
            a2a_targets=a2a_details,
        )

        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(
                f"{settings.atom_llm_url}/v1/chat/completions",
                headers={"Authorization": f"Bearer {settings.litellm_master_key}"},
                json={
                    "model": _CODEGEN_MODEL,
                    "messages": [{"role": "user", "content": codegen_prompt}],
                    "temperature": 0.2,
                },
            )
            resp.raise_for_status()
            agent_py = resp.json()["choices"][0]["message"]["content"]
            # Strip markdown code fences if present
            if agent_py.startswith("```"):
                lines = agent_py.splitlines()
                # Remove first and last fence lines
                agent_py = "\n".join(
                    line for line in lines[1:] if not line.strip().startswith("```")
                )

        yield _progress(step, "agent.py generated successfully")

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Local CI shortcut ─────────────────────────────────────────────────────
    # Local strategy: write scaffold files → docker build → deploy via runtime.
    if state.ci_target == "local":
        step = "build_local"
        try:
            image_tag, build_log = await _build_local_image(state, agent_py)
            yield _progress(step, f"Docker image built: {image_tag}")
        except Exception as exc:
            log.exception("deploy step %s failed", step)
            yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
            return

        step = "deployed"
        try:
            deployment_id = await _direct_deploy(
                state=state,
                image=image_tag,
                git_sha=None,
                message="Local build via ATOM Builder",
                owner_id=owner_id,
            )
            state.chat_url = f"/chat/{state.agent_id}"
            await save_state(redis, state)
            yield _progress(step, "Agent deployed to runtime", deployment_id=deployment_id)
            yield {"type": "done", "chat_url": state.chat_url}
        except Exception as exc:
            log.exception("deploy step %s failed", step)
            yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Step 3: Create GitLab repo ─────────────────────────────────────────────
    step = "repo_created"
    gitlab = GitLabService()
    try:
        repo_info = await gitlab.create_repo(state.agent_name or state.agent_id or "agent")
        state.gitlab_project_id = repo_info["id"]
        state.gitlab_repo_url = repo_info["web_url"]
        await save_state(redis, state)
        yield _progress(step, "GitLab repo created", url=state.gitlab_repo_url)

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Step 4: Set permissions ────────────────────────────────────────────────
    step = "permissions"
    try:
        await gitlab.set_permissions(state.gitlab_project_id)
        yield _progress(step, "Runner permissions configured")

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Step 5: Push scaffold files ────────────────────────────────────────────
    step = "pushed"
    try:
        files = {
            "agent.py": agent_py,
            "atom_agent.yaml": _build_atom_agent_yaml(state, gitlab.group),
            "Dockerfile": _build_dockerfile(gitlab.group),
            ".gitlab-ci.yml": _build_gitlab_ci(),
            "requirements.txt": _build_requirements(),
            "README.md": _build_readme(state),
        }
        commit_sha = await gitlab.push_files(state.gitlab_project_id, files)
        yield _progress(step, f"Files pushed — commit {commit_sha[:12]}", commit_sha=commit_sha)

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Step 6: Trigger pipeline + poll ───────────────────────────────────────
    step = "pipeline_start"
    try:
        pipeline_info = await gitlab.trigger_pipeline(state.gitlab_project_id, commit_sha)
        state.pipeline_id = pipeline_info["id"]
        state.pipeline_url = pipeline_info.get("web_url", "")
        await save_state(redis, state)
        yield _progress(
            step,
            f"CI pipeline #{state.pipeline_id} triggered",
            pipeline_id=state.pipeline_id,
            pipeline_url=state.pipeline_url,
        )

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # Poll pipeline
    elapsed = 0
    poll_interval = 10
    max_wait = 1800  # 30 minutes
    final_status = "unknown"
    while elapsed < max_wait:
        await asyncio.sleep(poll_interval)
        elapsed += poll_interval
        try:
            final_status = await gitlab.pipeline_status(state.gitlab_project_id, state.pipeline_id)
        except Exception as poll_exc:
            log.warning("pipeline poll error (will retry): %s", poll_exc)
            continue

        yield {
            "type": "progress",
            "step": "pipeline_poll",
            "message": f"Pipeline status: {final_status} ({elapsed}s elapsed)",
            "status": final_status,
            "elapsed": elapsed,
        }

        if final_status == "success":
            break
        if final_status in ("failed", "canceled", "skipped"):
            yield {
                "type": "error",
                "step": "pipeline_poll",
                "message": f"CI pipeline {final_status}. See: {state.pipeline_url}",
                "retryable": False,
            }
            return

    if final_status != "success":
        yield {
            "type": "error",
            "step": "pipeline_poll",
            "message": f"Pipeline timed out after {elapsed}s with status: {final_status}",
            "retryable": False,
        }
        return

    # ── Step 7: Deploy to runtime ──────────────────────────────────────────────
    step = "deployed"
    try:
        image = f"registry.gitlab.com/{gitlab.group}/{state.agent_name}:{commit_sha[:12]}"
        deployment_id = await _direct_deploy(
            state=state,
            image=image,
            git_sha=commit_sha,
            message=f"ATOM Builder — pipeline #{state.pipeline_id}",
            owner_id=owner_id,
        )
        state.chat_url = f"/chat/{state.agent_id}"
        await save_state(redis, state)
        yield _progress(step, "Agent deployed to runtime", deployment_id=deployment_id, image=image)

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Step 8: Done ───────────────────────────────────────────────────────────
    yield {"type": "done", "chat_url": state.chat_url}
