import asyncio
import hashlib
import json
import logging
import os
from typing import AsyncGenerator

import httpx

from ..config import get_settings
from ..database import get_conn
from ..services.builder_conversation import BuilderState, save_state
from ..services.builder import build_agent_py_prompt, _formatter_for_model
from ..agents.service import AgentCreatePayload, create_agent, issue_agent_jwt
from ..deployments.service import get_runtime_url

log = logging.getLogger(__name__)

_CODEGEN_MODEL = "gemini-3.1-pro-preview"
_HEAL_MAX_ATTEMPTS = 3  # max self-heal retries
_HEALTH_POLL_INTERVAL = 5  # seconds between health checks
_HEALTH_TIMEOUT = 120  # seconds to wait for container healthy


# ── Helper ─────────────────────────────────────────────────────────────────────


def _progress(step: str, message: str, **extra) -> dict:
    return {"type": "progress", "step": step, "message": message, **extra}


# ── Scaffold file builders ─────────────────────────────────────────────────────


def _build_atom_agent_yaml(state: BuilderState) -> str:
    return f"""# Agent configuration — generated by ATOM Builder
agent_id: "{state.agent_id}"
domain_id: "{state.domain_id}"
model: "{state.model}"
sdk_image: ""
"""


def _build_dockerfile() -> str:
    return """FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]
"""


def _build_requirements() -> str:
    return (
        "agentscope>=0.1.0\n"
        "fastapi>=0.110.0\n"
        "uvicorn[standard]>=0.29.0\n"
        "httpx>=0.27.0\n"
        "aiokafka>=0.11.0\n"
        "python-dotenv>=1.0.0\n"
    )


def _build_server_py() -> str:
    """Fixed server.py boilerplate — identical for every agent. Never changes."""
    return '''"""
server.py — ATOM agent HTTP server (auto-generated boilerplate, do not modify)
Agent logic lives in agent.py — edit that file to change agent behaviour.

Endpoints:
    GET  /healthz  — liveness probe (atom-runtime polls this)
    POST /run      — {"message": "..."} → {"reply": "...", "run_id": "..."}
"""
import json
import logging
import os
import time
import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone

import agentscope
import httpx
from agentscope.message import Msg
from fastapi import FastAPI
from pydantic import BaseModel

from agent import build_agent  # noqa: E402 — agent.py in same directory

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

AGENT_ID = os.environ.get("ATOM_AGENT_ID", "")
STUDIO_URL = os.environ.get("ATOM_STUDIO_URL", "http://atom-studio-api:3001")
KAFKA_BROKERS = os.environ.get("KAFKA_BROKERS", "")
KAFKA_TOPIC = "atom.agent.logs"

_kafka_producer = None


async def _init_kafka() -> None:
    global _kafka_producer
    if not KAFKA_BROKERS:
        log.info("KAFKA_BROKERS not set — log streaming disabled")
        return
    try:
        from aiokafka import AIOKafkaProducer  # noqa: PLC0415

        _kafka_producer = AIOKafkaProducer(
            bootstrap_servers=KAFKA_BROKERS,
            value_serializer=lambda v: json.dumps(v).encode(),
        )
        await _kafka_producer.start()
        log.info("Kafka producer connected → %s", KAFKA_BROKERS)
    except Exception as exc:
        log.warning("Kafka producer init failed: %s", exc)


async def _stop_kafka() -> None:
    if _kafka_producer:
        await _kafka_producer.stop()


async def _emit_log(message: str, source: str = "stdout") -> None:
    if not _kafka_producer:
        return
    try:
        await _kafka_producer.send(
            KAFKA_TOPIC,
            {
                "agent_id": AGENT_ID,
                "message": message,
                "source": source,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
        )
    except Exception:
        pass


async def _record_run(
    run_id: str,
    user_msg: str,
    reply: str,
    steps: list,
    latency_ms: int,
) -> None:
    if not AGENT_ID or not STUDIO_URL:
        return
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            await client.post(
                f"{STUDIO_URL}/api/agents/{AGENT_ID}/runs/",
                json={
                    "run_id": run_id,
                    "user_msg": user_msg,
                    "reply": reply,
                    "steps": steps,
                    "latency_ms": latency_ms,
                },
            )
    except Exception as exc:
        log.warning("record_run failed: %s", exc)


@asynccontextmanager
async def lifespan(app: FastAPI):
    await _init_kafka()
    yield
    await _stop_kafka()


# ── Agent init ─────────────────────────────────────────────────────────────────

agentscope.init()   # no studio_url — ATOM handles its own tracing
_agent = build_agent()

app = FastAPI(title="ATOM Agent", lifespan=lifespan)


# ── Endpoints ──────────────────────────────────────────────────────────────────


class RunRequest(BaseModel):
    message: str


class RunResponse(BaseModel):
    reply: str
    run_id: str


@app.get("/healthz")
async def healthz():
    return {"status": "ok"}


@app.post("/run", response_model=RunResponse)
async def run(req: RunRequest):
    run_id = str(uuid.uuid4())
    t0 = time.monotonic()

    await _emit_log(f"[request] {req.message}")

    response = await _agent(Msg(name="user", content=req.message, role="user"))

    blocks = response.get_content_blocks("text")
    reply = " ".join(b.get("text", "") for b in blocks) if blocks else str(response.content)
    latency_ms = int((time.monotonic() - t0) * 1000)

    await _emit_log(f"[reply] ({latency_ms}ms) {reply}")
    await _record_run(run_id, req.message, reply, [], latency_ms)

    return RunResponse(reply=reply, run_id=run_id)
'''


def _build_readme(state: BuilderState) -> str:
    return (
        f"# {state.agent_name}\n\nGenerated by ATOM Builder.\n\n## Intent\n{state.intent or ''}\n"
    )


# ── Local Docker build ────────────────────────────────────────────────────────


async def _build_local_image(state: BuilderState, agent_py: str) -> tuple[str, str]:
    """Build a Docker image locally and return (image_tag, build_log)."""
    import tempfile

    import docker as docker_sdk  # noqa: PLC0415

    image_name = (state.agent_name or state.agent_id or "agent").lower().replace(" ", "-")
    image_tag = f"atom-agent/{image_name}:latest"

    with tempfile.TemporaryDirectory() as tmpdir:
        for fname, content in {
            "agent.py": agent_py,
            "server.py": _build_server_py(),
            "requirements.txt": _build_requirements(),
            "Dockerfile": _build_dockerfile(),
            "atom_agent.yaml": _build_atom_agent_yaml(state),
            "README.md": _build_readme(state),
        }.items():
            with open(os.path.join(tmpdir, fname), "w") as fh:
                fh.write(content)

        loop = asyncio.get_event_loop()

        def _docker_build():
            client = docker_sdk.from_env()
            _, log_output = client.images.build(path=tmpdir, tag=image_tag, rm=True, forcerm=True)
            lines = [
                chunk.get("stream", chunk.get("status", ""))
                for chunk in log_output
                if isinstance(chunk, dict)
            ]
            return "\n".join(line for line in lines if line.strip())

        build_log = await loop.run_in_executor(None, _docker_build)

    return image_tag, build_log


# ── Docker health / log helpers ───────────────────────────────────────────────


async def _poll_container_health(container_name: str) -> tuple[str, str]:
    """
    Poll until the container is running+healthy or exits.

    Returns (status, logs) where status is:
      "healthy"  — container running without crash
      "failed"   — container exited / unhealthy
      "timeout"  — health poll timed out
    """
    import docker as docker_sdk  # noqa: PLC0415

    loop = asyncio.get_event_loop()

    def _check():
        try:
            client = docker_sdk.from_env()
            c = client.containers.get(container_name)
            status = c.status  # "running", "exited", "created", etc.
            logs = c.logs(tail=80).decode("utf-8", errors="replace")
            return status, logs
        except docker_sdk.errors.NotFound:
            return "not_found", ""
        except Exception as exc:
            return "error", str(exc)

    elapsed = 0
    while elapsed < _HEALTH_TIMEOUT:
        status, logs = await loop.run_in_executor(None, _check)
        if status == "running":
            # Check if process has been up > 3 seconds without crash
            if elapsed >= 6:
                return "healthy", logs
        elif status in ("exited", "dead"):
            return "failed", logs
        elif status == "not_found":
            if elapsed > 30:
                return "timeout", "Container not found after 30s"
        await asyncio.sleep(_HEALTH_POLL_INTERVAL)
        elapsed += _HEALTH_POLL_INTERVAL

    _, logs = await loop.run_in_executor(None, _check)
    return "timeout", logs


async def _get_container_logs(container_name: str) -> str:
    """Get recent Docker container logs."""
    import docker as docker_sdk  # noqa: PLC0415

    loop = asyncio.get_event_loop()

    def _logs():
        try:
            client = docker_sdk.from_env()
            c = client.containers.get(container_name)
            return c.logs(tail=100).decode("utf-8", errors="replace")
        except Exception as exc:
            return f"Could not get logs: {exc}"

    return await loop.run_in_executor(None, _logs)


# ── Self-healing codegen ──────────────────────────────────────────────────────


async def _generate_fix(
    original_agent_py: str,
    error_logs: str,
    intent: str,
    model_name: str,
    atom_llm_url: str,
    litellm_master_key: str,
) -> str:
    """Ask the LLM to fix agent.py given the container error logs."""
    formatter_import, formatter_instance = _formatter_for_model(model_name)

    fix_prompt = f"""Fix the agent.py below. The container crashed — error logs are shown.

agent.py contains ONE function: `build_agent() -> ReActAgent`.
The surrounding server (FastAPI, Kafka, /run, /healthz) is in a fixed server.py — do not reproduce it.

## Broken agent.py
```python
{original_agent_py}
```

## Container error logs
```
{error_logs}
```

## Intent: {intent}

## Fix rules
- Output ONLY agent.py with only `build_agent() -> ReActAgent` — no server, no FastAPI, no Kafka
- Imports: `agentscope.agent` (singular), `agentscope.model` (singular), `agentscope.formatter`, `agentscope.tool`
- `formatter=OpenAIChatFormatter()` always — never any other formatter
- `ReActAgent` requires `formatter=` positional arg — never omit
- ALL tool functions MUST return ToolResponse — never str/dict/None
  Use: `return ToolResponse(content=[TextBlock(type="text", text=result)])`
  Import: `from agentscope.tool import Toolkit, ToolResponse; from agentscope.message import TextBlock`
- For HITL: call `request_human_decision()` inside a tool function, wrap in ToolResponse
- Tools registered via `toolkit.register_tool_function(func)` — no `agent.use_tool()`
- No `agentscope.init()` in agent.py — server.py handles that
- No markdown fences, pure Python only
"""

    async with httpx.AsyncClient(timeout=120.0) as client:
        resp = await client.post(
            f"{atom_llm_url}/v1/chat/completions",
            headers={"Authorization": f"Bearer {litellm_master_key}"},
            json={
                "model": _CODEGEN_MODEL,
                "messages": [{"role": "user", "content": fix_prompt}],
                "temperature": 0.1,
            },
        )
        resp.raise_for_status()
        fixed = resp.json()["choices"][0]["message"]["content"]

    # Strip fences if present
    if fixed.startswith("```"):
        lines = fixed.splitlines()
        fixed = "\n".join(line for line in lines[1:] if not line.strip().startswith("```"))

    return fixed.strip()


# ── Direct deploy (bypasses HITL — builder-only path) ─────────────────────────


async def _direct_deploy(
    state: BuilderState,
    image: str,
    git_sha: str | None,
    message: str,
    owner_id: str,
) -> str:
    """
    Insert deployment row, issue a pod JWT, call atom-runtime directly.
    Returns the deployment_id string.  Bypasses HITL — builder flow only.
    """
    manifest = json.dumps({"image": image, "git_sha": git_sha, "message": message})

    async with get_conn() as conn:
        deployment = await conn.fetchrow(
            """
            WITH v AS (
                SELECT COALESCE(MAX(version), 0) + 1 AS next_version
                FROM deployments WHERE agent_id = $1
            )
            INSERT INTO deployments (agent_id, version, manifest_json, status, submitted_by)
            SELECT $1, next_version, $2::jsonb, 'pending', $3::uuid
            FROM v
            RETURNING id
            """,
            state.agent_id,
            manifest,
            owner_id,
        )
        deployment_id = str(deployment["id"])

        agent_jwt = issue_agent_jwt(state.agent_id, state.domain_id or "")
        token_hash = hashlib.sha256(agent_jwt.encode()).hexdigest()
        await conn.execute(
            "UPDATE agent_tokens SET revoked_at=now() "
            "WHERE agent_id=$1 AND revoked_at IS NULL AND token_type='pod'",
            state.agent_id,
        )
        await conn.execute(
            "INSERT INTO agent_tokens (agent_id, token_hash, token_type) VALUES ($1,$2,'pod')",
            state.agent_id,
            token_hash,
        )

    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(
            f"{get_runtime_url()}/runtime/deploy",
            json={
                "deployment_id": deployment_id,
                "agent_id": state.agent_id,
                "domain_id": state.domain_id or "",
                "image": image,
                "agent_jwt": agent_jwt,
            },
        )
        resp.raise_for_status()

    return deployment_id


# ── Local deploy with health check + self-healing ─────────────────────────────


async def _deploy_local_with_healing(
    state: BuilderState,
    agent_py: str,
    owner_id: str,
    redis,
) -> AsyncGenerator[dict, None]:
    """
    Build image → deploy → poll health → self-heal up to _HEAL_MAX_ATTEMPTS times.
    """
    settings = get_settings()
    container_name = f"agent-{state.agent_id}"

    for attempt in range(1, _HEAL_MAX_ATTEMPTS + 1):
        label = f"(attempt {attempt}/{_HEAL_MAX_ATTEMPTS})" if attempt > 1 else ""

        # Build
        step = "build_local"
        try:
            image_tag, _ = await _build_local_image(state, agent_py)
            yield _progress(step, f"Docker image built: {image_tag} {label}")
        except Exception as exc:
            yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
            return

        # Deploy
        step = "deployed"
        try:
            deployment_id = await _direct_deploy(
                state=state,
                image=image_tag,
                git_sha=None,
                message=f"ATOM Builder local deploy {label}",
                owner_id=owner_id,
            )
            yield _progress(step, f"Container starting… {label}", deployment_id=deployment_id)
        except Exception as exc:
            yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
            return

        # Poll health
        step = "health_check"
        yield _progress(step, "Waiting for container to become healthy…")
        health_status, logs = await _poll_container_health(container_name)

        if health_status == "healthy":
            state.chat_url = f"/domains/{state.domain_id}/agents/{state.agent_id}/conversations"
            await save_state(redis, state)
            yield _progress("live", "Agent is running and healthy")
            yield {"type": "done", "chat_url": state.chat_url}
            return

        # Container failed — self-heal if attempts remain
        error_snippet = logs[-2000:] if len(logs) > 2000 else logs
        yield {
            "type": "progress",
            "step": "container_error",
            "message": f"Container {'crashed' if health_status == 'failed' else 'timed out'}",
            "logs": error_snippet,
        }

        if attempt >= _HEAL_MAX_ATTEMPTS:
            yield {
                "type": "error",
                "step": "container_error",
                "message": f"Container failed after {_HEAL_MAX_ATTEMPTS} attempts. Last error:\n{error_snippet[:500]}",
                "retryable": False,
                "logs": error_snippet,
            }
            return

        # Analyse and fix
        step = "healing"
        yield _progress(step, f"Analysing error… (attempt {attempt}/{_HEAL_MAX_ATTEMPTS})")
        try:
            agent_py = await _generate_fix(
                original_agent_py=agent_py,
                error_logs=error_snippet,
                intent=state.intent or "",
                model_name=state.model or "gemini-2.5-flash",
                atom_llm_url=settings.atom_llm_url,
                litellm_master_key=settings.litellm_master_key,
            )
            yield _progress(step, "Code fix generated — rebuilding…")
        except Exception as exc:
            yield {
                "type": "error",
                "step": step,
                "message": f"Failed to generate fix: {exc}",
                "retryable": False,
            }
            return

    # Should not reach here
    yield {
        "type": "error",
        "step": "healing",
        "message": "Max heal attempts exhausted",
        "retryable": False,
    }


# ── Main deploy generator ──────────────────────────────────────────────────────


async def run_deploy(
    state: BuilderState,
    owner_id: str,
    redis,
) -> AsyncGenerator[dict, None]:
    """
    Full deploy sequence with SSE events.
    provision → codegen → docker build → deploy → health check → self-heal
    """
    settings = get_settings()

    # ── Step 1: Provision ─────────────────────────────────────────────────────
    step = "provisioning"
    try:
        payload = AgentCreatePayload(
            name=state.agent_name or "unnamed-agent",
            description=state.intent,
            allowed_models=[state.model] if state.model else ["gemini-2.5-flash"],
        )
        agent_dict, _raw_jwt = await create_agent(state.domain_id or "", payload, owner_id)
        state.agent_id = str(agent_dict["id"])
        yield _progress(step, f"Provisioned: {state.agent_id}")

        if state.tools or state.skills:
            async with get_conn() as conn:
                for tool_name in state.tools:
                    row = await conn.fetchrow(
                        "SELECT id FROM tools WHERE name=$1 LIMIT 1", tool_name
                    )
                    if row:
                        await conn.execute(
                            "INSERT INTO agent_tools (agent_id, tool_id) VALUES ($1,$2) ON CONFLICT DO NOTHING",
                            state.agent_id,
                            row["id"],
                        )
                for skill_name in state.skills:
                    row = await conn.fetchrow(
                        "SELECT id FROM skills WHERE name=$1 LIMIT 1", skill_name
                    )
                    if row:
                        await conn.execute(
                            "INSERT INTO agent_skills (agent_id, skill_id) VALUES ($1,$2) ON CONFLICT DO NOTHING",
                            state.agent_id,
                            row["id"],
                        )

        await save_state(redis, state)

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Step 2: Codegen ───────────────────────────────────────────────────────
    step = "codegen"
    agent_py = ""
    try:
        tool_objects: list[dict] = []
        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                resp = await client.get(
                    f"{settings.atom_llm_url}/mcp/tools",
                    headers={"Authorization": f"Bearer {settings.litellm_master_key}"},
                )
                resp.raise_for_status()
                all_tools = resp.json()
                if isinstance(all_tools, dict):
                    all_tools = all_tools.get("tools", [])
                tool_objects = [t for t in all_tools if t.get("name") in state.tools]
        except Exception as fetch_exc:
            log.warning("codegen: could not fetch tools — %s", fetch_exc)

        a2a_details: list[dict] = []
        if state.a2a_targets:
            async with get_conn() as conn:
                for target_name in state.a2a_targets:
                    row = await conn.fetchrow(
                        "SELECT id, name, description FROM agents WHERE name=$1 AND domain_id=$2",
                        target_name,
                        state.domain_id,
                    )
                    if row:
                        a2a_details.append(dict(row))

        codegen_prompt = build_agent_py_prompt(
            intent=state.intent or "",
            model_name=state.model or "gemini-2.5-flash",
            tools=tool_objects,
            skills=state.skills,
            a2a_targets=a2a_details,
        )

        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(
                f"{settings.atom_llm_url}/v1/chat/completions",
                headers={"Authorization": f"Bearer {settings.litellm_master_key}"},
                json={
                    "model": _CODEGEN_MODEL,
                    "messages": [{"role": "user", "content": codegen_prompt}],
                    "temperature": 0.2,
                },
            )
            resp.raise_for_status()
            agent_py = resp.json()["choices"][0]["message"]["content"]
            if agent_py.startswith("```"):
                lines = agent_py.splitlines()
                agent_py = "\n".join(
                    line for line in lines[1:] if not line.strip().startswith("```")
                )

        yield _progress(step, "agent.py generated")

    except Exception as exc:
        log.exception("deploy step %s failed", step)
        yield {"type": "error", "step": step, "message": str(exc), "retryable": False}
        return

    # ── Build and deploy locally ──────────────────────────────────────────────
    async for event in _deploy_local_with_healing(state, agent_py, owner_id, redis):
        yield event
