package ci

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// GitHub triggers a GitHub Actions workflow_dispatch and waits for it to finish.
// The agent repo must have .github/workflows/atom-build.yml (generated by atom create).
type GitHub struct {
	Token string
}

func (g *GitHub) TriggerBuild(repoURL, branch, imageTag string) (runURL string, imageRef string, err error) {
	owner, repo, err := parseGitHubURL(repoURL)
	if err != nil {
		return "", "", err
	}
	imageRef = fmt.Sprintf("ghcr.io/%s/%s:%s", strings.ToLower(owner), strings.ToLower(repo), imageTag)

	body, _ := json.Marshal(map[string]any{
		"ref":    branch,
		"inputs": map[string]string{"image_tag": imageTag},
	})
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/actions/workflows/atom-build.yml/dispatches", owner, repo)
	req, _ := http.NewRequest(http.MethodPost, url, bytes.NewReader(body))
	req.Header.Set("Authorization", "Bearer "+g.Token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", fmt.Errorf("trigger workflow: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusNoContent {
		raw, _ := io.ReadAll(resp.Body)
		return "", "", fmt.Errorf("GitHub API %d: %s", resp.StatusCode, string(raw))
	}
	return fmt.Sprintf("https://github.com/%s/%s/actions", owner, repo), imageRef, nil
}

func (g *GitHub) WaitForBuild(repoURL, branch string, timeout time.Duration) error {
	owner, repo, err := parseGitHubURL(repoURL)
	if err != nil {
		return err
	}

	deadline := time.Now().Add(timeout)
	// Give the API a few seconds to register the new run.
	time.Sleep(5 * time.Second)

	for time.Now().Before(deadline) {
		url := fmt.Sprintf(
			"https://api.github.com/repos/%s/%s/actions/workflows/atom-build.yml/runs?branch=%s&per_page=1",
			owner, repo, branch,
		)
		req, _ := http.NewRequest(http.MethodGet, url, nil)
		req.Header.Set("Authorization", "Bearer "+g.Token)
		req.Header.Set("Accept", "application/vnd.github+json")

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			time.Sleep(10 * time.Second)
			continue
		}
		var result struct {
			Runs []struct {
				Status     string `json:"status"`
				Conclusion string `json:"conclusion"`
			} `json:"workflow_runs"`
		}
		_ = json.NewDecoder(resp.Body).Decode(&result)
		resp.Body.Close()

		if len(result.Runs) > 0 {
			run := result.Runs[0]
			switch run.Status {
			case "completed":
				if run.Conclusion == "success" {
					return nil
				}
				return fmt.Errorf("workflow finished with conclusion: %s", run.Conclusion)
			case "in_progress", "queued", "waiting":
				fmt.Printf("  [github] workflow %s…\n", run.Status)
			}
		}
		time.Sleep(15 * time.Second)
	}
	return fmt.Errorf("timed out waiting for GitHub Actions workflow to complete")
}

func parseGitHubURL(rawURL string) (owner, repo string, err error) {
	u := strings.TrimSuffix(strings.TrimPrefix(rawURL, "https://github.com/"), ".git")
	parts := strings.SplitN(strings.TrimPrefix(u, "/"), "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("invalid GitHub URL %q — expected https://github.com/owner/repo", rawURL)
	}
	return parts[0], parts[1], nil
}
