package ci

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// GitLab triggers and monitors a GitLab CI pipeline.
// The agent repo must have .gitlab-ci.yml generated by atom create.
type GitLab struct {
	Token string
}

// TriggerBuild triggers a GitLab CI pipeline with ATOM_BUILD=true and the given image tag.
// sdkImage is injected as SDK_IMAGE pipeline variable when non-empty.
// Returns the pipeline ID, pipeline web URL (for log links), and the image ref that will be pushed.
func (g *GitLab) TriggerBuild(repoURL, branch, imageTag, sdkImage string) (pipelineID int, webURL string, imageRef string, err error) {
	host, projectPath, err := parseGitLabURL(repoURL)
	if err != nil {
		return 0, "", "", err
	}
	encodedPath := url.PathEscape(projectPath)
	imageRef = fmt.Sprintf("registry.%s/%s:%s", host, strings.ToLower(projectPath), imageTag)

	vars := []map[string]string{
		{"key": "ATOM_BUILD", "value": "true"},
		{"key": "ATOM_IMAGE_TAG", "value": imageTag},
	}
	if sdkImage != "" {
		vars = append(vars, map[string]string{"key": "SDK_IMAGE", "value": sdkImage})
	}

	body, _ := json.Marshal(map[string]any{
		"ref":       branch,
		"variables": vars,
	})
	apiURL := fmt.Sprintf("https://%s/api/v4/projects/%s/pipeline", host, encodedPath)
	req, _ := http.NewRequest(http.MethodPost, apiURL, bytes.NewReader(body))
	req.Header.Set("Authorization", "Bearer "+g.Token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return 0, "", "", fmt.Errorf("trigger pipeline: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusForbidden {
		return 0, "", "", fmt.Errorf("GitLab API %d: invalid or missing credentials — check your PAT has 'api' scope", resp.StatusCode)
	}
	if resp.StatusCode >= 300 {
		raw, _ := io.ReadAll(resp.Body)
		return 0, "", "", fmt.Errorf("GitLab API %d: %s", resp.StatusCode, string(raw))
	}
	var result struct {
		ID     int    `json:"id"`
		WebURL string `json:"web_url"`
	}
	_ = json.NewDecoder(resp.Body).Decode(&result)
	return result.ID, result.WebURL, imageRef, nil
}

// WaitForBuild polls the pipeline every 30 seconds until it completes or times out.
// pipelineURL is included in error messages for quick access to job logs.
func (g *GitLab) WaitForBuild(repoURL string, pipelineID int, pipelineURL string, timeout time.Duration) error {
	host, projectPath, err := parseGitLabURL(repoURL)
	if err != nil {
		return err
	}
	encodedPath := url.PathEscape(projectPath)
	apiURL := fmt.Sprintf("https://%s/api/v4/projects/%s/pipelines/%d", host, encodedPath, pipelineID)

	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		req, _ := http.NewRequest(http.MethodGet, apiURL, nil)
		req.Header.Set("Authorization", "Bearer "+g.Token)

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			time.Sleep(10 * time.Second)
			continue
		}
		var result struct {
			Status string `json:"status"`
		}
		_ = json.NewDecoder(resp.Body).Decode(&result)
		resp.Body.Close()

		switch result.Status {
		case "success":
			return nil
		case "failed", "canceled", "skipped":
			if pipelineURL != "" {
				return fmt.Errorf("pipeline %s — see logs: %s", result.Status, pipelineURL)
			}
			return fmt.Errorf("pipeline finished with status: %s", result.Status)
		default:
			fmt.Printf("  [gitlab] pipeline %s…\n", result.Status)
		}
		time.Sleep(30 * time.Second)
	}
	return fmt.Errorf("timed out waiting for GitLab pipeline to complete")
}

// CrossGroupWarning returns a non-empty string if sdkImage and the agent's project path
// are in different top-level GitLab groups. Cross-group pulls require a deploy token.
func CrossGroupWarning(sdkImage, agentProjectPath string) string {
	if !strings.HasPrefix(sdkImage, "registry.gitlab.com/") {
		return ""
	}
	sdkPath := strings.TrimPrefix(sdkImage, "registry.gitlab.com/")
	sdkGroup := strings.SplitN(sdkPath, "/", 2)[0]
	agentGroup := strings.SplitN(agentProjectPath, "/", 2)[0]
	if sdkGroup == "" || agentGroup == "" || sdkGroup == agentGroup {
		return ""
	}
	return fmt.Sprintf(
		"⚠  sdk_image group %q ≠ agent group %q — if the build fails pulling the base image,\n"+
			"   add a group deploy token at:\n"+
			"   https://gitlab.com/groups/%s/-/settings/repository#js-deploy-tokens",
		sdkGroup, agentGroup, sdkGroup)
}

func parseGitLabURL(rawURL string) (host, projectPath string, err error) {
	u, err := url.Parse(rawURL)
	if err != nil {
		return "", "", fmt.Errorf("invalid GitLab URL: %w", err)
	}
	if u.Host == "" {
		return "", "", fmt.Errorf("invalid GitLab URL %q", rawURL)
	}
	path := strings.TrimSuffix(strings.TrimPrefix(u.Path, "/"), ".git")
	if path == "" {
		return "", "", fmt.Errorf("invalid GitLab URL %q — expected https://gitlab.com/owner/repo", rawURL)
	}
	return u.Host, path, nil
}
