package ci

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// GitLab triggers a GitLab CI pipeline and waits for it to finish.
// The agent repo must have .gitlab-ci.yml (generated by atom create).
type GitLab struct {
	Token string
}

func (g *GitLab) TriggerBuild(repoURL, branch, imageTag string) (pipelineID int, imageRef string, err error) {
	host, projectPath, err := parseGitLabURL(repoURL)
	if err != nil {
		return 0, "", err
	}
	encodedPath := url.PathEscape(projectPath)
	imageRef = fmt.Sprintf("registry.%s/%s:%s", host, strings.ToLower(projectPath), imageTag)

	body, _ := json.Marshal(map[string]any{
		"ref": branch,
		"variables": []map[string]string{
			{"key": "IMAGE_TAG", "value": imageTag},
		},
	})
	apiURL := fmt.Sprintf("https://%s/api/v4/projects/%s/pipeline", host, encodedPath)
	req, _ := http.NewRequest(http.MethodPost, apiURL, bytes.NewReader(body))
	req.Header.Set("Authorization", "Bearer "+g.Token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return 0, "", fmt.Errorf("trigger pipeline: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		raw, _ := io.ReadAll(resp.Body)
		return 0, "", fmt.Errorf("GitLab API %d: %s", resp.StatusCode, string(raw))
	}
	var result struct {
		ID int `json:"id"`
	}
	_ = json.NewDecoder(resp.Body).Decode(&result)
	return result.ID, imageRef, nil
}

func (g *GitLab) WaitForBuild(repoURL string, pipelineID int, timeout time.Duration) error {
	host, projectPath, err := parseGitLabURL(repoURL)
	if err != nil {
		return err
	}
	encodedPath := url.PathEscape(projectPath)
	apiURL := fmt.Sprintf("https://%s/api/v4/projects/%s/pipelines/%d", host, encodedPath, pipelineID)

	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		req, _ := http.NewRequest(http.MethodGet, apiURL, nil)
		req.Header.Set("Authorization", "Bearer "+g.Token)

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			time.Sleep(10 * time.Second)
			continue
		}
		var result struct {
			Status string `json:"status"`
		}
		_ = json.NewDecoder(resp.Body).Decode(&result)
		resp.Body.Close()

		switch result.Status {
		case "success":
			return nil
		case "failed", "canceled", "skipped":
			return fmt.Errorf("pipeline finished with status: %s", result.Status)
		default:
			fmt.Printf("  [gitlab] pipeline %s…\n", result.Status)
		}
		time.Sleep(15 * time.Second)
	}
	return fmt.Errorf("timed out waiting for GitLab pipeline to complete")
}

func parseGitLabURL(rawURL string) (host, projectPath string, err error) {
	u, err := url.Parse(rawURL)
	if err != nil {
		return "", "", fmt.Errorf("invalid GitLab URL: %w", err)
	}
	if u.Host == "" {
		return "", "", fmt.Errorf("invalid GitLab URL %q", rawURL)
	}
	path := strings.TrimSuffix(strings.TrimPrefix(u.Path, "/"), ".git")
	if path == "" {
		return "", "", fmt.Errorf("invalid GitLab URL %q — expected https://gitlab.com/owner/repo", rawURL)
	}
	return u.Host, path, nil
}
